### ISSUE TITLE
Nothing is working in page after calling appversion

### ISSUE THREAD

**Issue by vishalv26** [whiteoctober/cordova-plugin-app-version#102]
example : 

    alert(this.file.externalCacheDirectory); //returns proper directory when called above
    this.appVersion.getPackageName().then(function (getPackageName) {
    alert(getPackageName);
    });
bit not getting alert if called like this

    this.appVersion.getPackageName().then(function (getPackageName) {
    alert(this.file.externalCacheDirectory);
});

i assume it clears everything in this.* if called once

**Comment by DennisSmolek** [comment]
Im guessing your scope for `this` inside the promise refers to that function and not the outer scope.

**Comment by DennisSmolek** [comment]
try:
```
var that = this;
this.appVersion.getPackageName().then(function (getPackageName) {
    alert(that.file.externalCacheDirectory);
});
```
