### ISSUE TITLE
Ionic --prod mode does not build

### ISSUE THREAD

**Issue by sonugpc** [whiteoctober/cordova-plugin-app-version#109]
Hi App version Plugin is creating a problem while generating --prod version of App

Unexpected value 'AppVersion in F:/D/Projects/link
        /node_modules/@ionic-native/app-version/ngx/index.d.ts' declared by the module
            'AppModule in /src/app/app.module.ts'. Please add a
            @Pipe/@Directive/@Component annotation.

**Comment by LouAdrien** [comment]
Same here, fix?
