### ISSUE TITLE
App version displayed as null on iOS

### ISSUE THREAD

**Issue by shane1090** [whiteoctober/cordova-plugin-app-version#14]
Just installed this plugin and it's working fine on Android but when viewed on iOS it displays as 'null'. This is using an iPhone 4S with iOS version 7.1.1.

Any ideas on how to get the version number displaying correctly?

**Comment by mattbowen** [comment]
Using Cordova 5.0, I was running into the same problem as @oliversalzburg. I resolved it by following the advice from http://stackoverflow.com/a/23934028 and adding AppVersion.m to my Compile Sources manually. I looked at the plugin.xml, but I can't see what's wrong that's has cordova not doing that automatically.

**Comment by leomelin** [comment]
Solution by @mattbowen helped me as well. Great!

**Comment by jacobg** [comment]
The Compile Sources solution also fixed this issue for me.

**Comment by Drarok** [comment]
It seems people have found the fix for this in the comments, so I'll close it.

**Comment by karuppasami6492** [comment]
Have you wrapped the call in platform.ready()?
