### ISSUE TITLE
Causes ProcessMessage Error

### ISSUE THREAD

**Issue by kornatzky** [whiteoctober/cordova-plugin-app-version#26]
Using PhoneGap version: 3.6.0-0.21.19, Android: 4.4.4

After the call:

cordova.getAppVersion().then(function (version) {

   // callback - do something

});

it starts executing the callback, and then it issues an error seen in Eclipse logical:

 "processMessage failed: Message: S01 AppVersion970924709 s1.0.0", source: file:///android_asset/www/cordova.js (1060)

ans stops executing the callback

Would appreciate any insight.

**Comment by Drarok** [comment]
Closing this as I can't replicate the problem.
