### ISSUE TITLE
app version missing the version number (only build version) in iOS

### ISSUE THREAD

**Issue by louisdoe** [whiteoctober/cordova-plugin-app-version#27]
Hi

my app version is 114 (1.032) in itunes connect, but the plugin only returns 114.

It should return the same number as the one set up in config.xml : 1.032
Thanks

**Comment by kaidokert** [comment]
For iOS the current approach is definitely falling short. Plugin should be able to obtain both the "marketing" version and build numbers. Trying one and then the other is not correct.
These two can be vastly different identifiers, with marketing version following apple mandated "x.y.z" scheme and build version being whatever: "frogs-koalas" if you like. 
hockeyapp for instance displays "x.y.z (build)" for iOS apps.

**Comment by Drarok** [comment]
`getVersionCode` appears to return the value of `CFBundleVersion` in the current version.
