### ISSUE TITLE
what is the latest new about plugin 0.1.5

### ISSUE THREAD

**Issue by bau720123** [whiteoctober/cordova-plugin-app-version#31]
hi
I saw in cordova.io have a new version 0.1.5
http://plugins.cordova.io/#/package/uk.co.whiteoctober.cordova.appversion

but in this page only update to 0.1.4
https://build.phonegap.com/plugins/984

so...is there any difference or update information ?

**Comment by rjmunro** [comment]
See https://github.com/whiteoctober/cordova-plugin-app-version/blob/develop/CHANGELOG.md for change information.

I can't figure out how to submit the new version to https://build.phonegap.com/plugins. It says "Please upgrade your PhoneGap Build account to submit a plugin". As I don't use phonegap, only cordova and ionic, I don't want to pay to upgrade my account. I am uploading my plugin as a favour to them.

**Comment by bau720123** [comment]
got it ~
thanks @rjmunro
