### ISSUE TITLE
Cordova warning

### ISSUE THREAD

**Issue by pcrombach** [whiteoctober/cordova-plugin-app-version#37]
AppVersion.m:24:32: 'toSuccessCallbackString:' is deprecated: Deprecated in Cordova 3.6. Use the CDVCommandDelegate method sendPluginResult:callbackId instead. This will be removed in 4.0.0

**Comment by kwoxford** [comment]
I'm getting this too. It might explain some recent bugginess in my apps.

**Comment by Libbux** [comment]
Confirmed in Cordova v3.7.0.

**Comment by Drarok** [comment]
This has been fixed in an earlier version, so I'm closing this issue.
