### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by schnti** [whiteoctober/cordova-plugin-app-version#43]
Please add the support for windows (Cordova 3.8.*). Not only wp8 and windows8.
Thx.

**Comment by filfat** [comment]
Bump, Windows 10 support would be great :+1:

**Comment by candidodmv** [comment]
@filfat do you know if there is support for Windows Phone Universal App?

Thanks

**Comment by candidodmv** [comment]
There is a current PR with this issue #67

**Comment by richsage** [comment]
If someone is able to test and verify #67 with a Windows Phone device (I don't have one), then I can get this merged.

**Comment by candidodmv** [comment]
Thanks @richsage. I will do that!

**Comment by candidodmv** [comment]
I done the tests on NOKIA Lumia 625 with Windows Phone 8.1 and All methods works except one : `getAppName`

I made some changes and add the comment direct to PR #67, follow prints, of tests done on the above cited device and Android Moto E 2th with Android 6.0.

![screenshot_20160331-102538](https://cloud.githubusercontent.com/assets/1034797/14177425/978a6694-f72c-11e5-8ba4-087ebc3c8b6f.png)
![screenshot_20160331-102546](https://cloud.githubusercontent.com/assets/1034797/14177426/978ab842-f72c-11e5-913b-0c8f6a5c1a5f.png)
![wp_ss_20160331_0001](https://cloud.githubusercontent.com/assets/1034797/14177423/9788de8c-f72c-11e5-9d3b-566c77ab2b47.jpg)
![wp_ss_20160331_0002](https://cloud.githubusercontent.com/assets/1034797/14177424/978a1072-f72c-11e5-99d0-b83fbfe9363d.jpg)

**Comment by candidodmv** [comment]
I can share the code project if is necessary

**Comment by filfat** [comment]
@candidodmv this is a request for UWP support not Silverlight 8.1.
You'll have to build it using "Windows-AnyCPU" in a UWP project (http://taco.visualstudio.com/en-us/docs/run-app-windows/)

**Comment by candidodmv** [comment]
But my devices target is Windows Phone 8.1 and above, in this case can't choose "Windows-AnyCPU"

**Comment by stevesum** [comment]
The solution for the windows universal apps if you modify the plugin.xml.
<platform name="windows"> instead of <platform name="windows8">

**Comment by stevesum** [comment]
The solution for the windows universal app if you modify the plugin.xm
`<platform name="windows">`
instead of
`<platform name="windows8">`

**Comment by kutomer** [comment]
+1

**Comment by filfat** [comment]
@candidodmv Again this issue is about the Windows platform, not the Windows Phone 8.1 platform they're two entirely different platforms on Cordova. That it works in your 8.1 project says nothing about it working on UWP (Windows 10).

**Comment by Drarok** [comment]
There appears to be a `windows` entry in `plugin.xml` now, so I'm closing this issue.
