### ISSUE TITLE
windows commandProxy not found

### ISSUE THREAD

**Issue by deliriousrhino** [whiteoctober/cordova-plugin-app-version#44]
On the windows platform when I add this plugin I get the error 
module cordova/windows8/commandproxy not found
I installed using the cordova CLI

**Comment by rjmunro** [comment]
Is this: https://github.com/deliriousrhino/cordova-plugin-app-version/commit/819ab599a80b51f7c53d04905081ef38d2b31db9 the fix? I've made a PR from that: #47

**Comment by deliriousrhino** [comment]
Yes this fixes the issue for me.

**Comment by Rezoseansstudios** [comment]
what does libfunc_require:(12, 1-44): module 'randomvoice' not found mean
