### ISSUE TITLE
Error when using Ripple

### ISSUE THREAD

**Issue by mariusbancila** [whiteoctober/cordova-plugin-app-version#45]
Hi,

I'm using the latest version of the plugin in a Cordova project. This is my code:

cordova.getAppVersion.getVersionNumber(function (version) {
   $scope.versionNumber = version;
});

When using the emulator or a real device it all works well. But when using Ripple as the target, I get the following error:

![pluginerror](https://cloud.githubusercontent.com/assets/5336650/7468444/58d85ce6-f311-11e4-8c43-08e8defb8b94.png)

What can be the problem? It's annoying because I use Ripple for most of development.

Thank you.

**Comment by boynet** [comment]
its emultaor.. they dont have this getVersionNumber they tell you to give them some example data that you want to get back from that call

**Comment by mariusbancila** [comment]
Of course, not, this is what the plugin is providing, right? But can it be extended to support Ripple as a platform (just as it does with android, ios, windows8, wp8, etc.)?

**Comment by boynet** [comment]
and from where it will get the version? as ripple its just running it in the browser not in cordova.. I think you should hanlde it yourself, just check if you are in cordva than use cordova plugin, if not in cordova than find a way to get the version and return it

**Comment by mariusbancila** [comment]
Well, it could return null or undefined or empty string, but not pop-up the annoying window.

Well, the idea to check the platform before using the plugin is all right. I got it to work this way.

**Comment by rjmunro** [comment]
@mariusbancila Is there a standard way that a plugin can add ripple emulation as a platform? What do other plugins do?

I don't want to have code to detect ripple and behave differently if it is installed that gets included in every real app whether it uses ripple or not - that seems like a bad idea.

**Comment by Drarok** [comment]
I don't actually know what ripple is, nor if this is still an issue. @mariusbancila could you elaborate or confirm if this is no longer required?

**Comment by DennisSmolek** [comment]
Ripple seems to no longer be maintained, I'm closing this issue unless more requests return.
