### ISSUE TITLE
some issues feedback to you

### ISSUE THREAD

**Issue by bau720123** [whiteoctober/cordova-plugin-app-version#52]
hi @rjmunro 
when I use "getAppName"，"getPackageName"，"getVersionCode"

in android and iOS，work perfect
but in wp8，it will trigger "nothing" (no any reflect)，is it because wp8 not ready to support these attribute ?

**Comment by rjmunro** [comment]
Those functions are not supported in WP8 at the moment. I don't have a windows phone or even a windows computer, so I am not able to work on them.

Pull requests to add those features would be welcome.

**Comment by bau720123** [comment]
got it
thanks @rjmunro
