### ISSUE TITLE
[not a issue] plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [whiteoctober/cordova-plugin-app-version#53]
hi @rjmunro 

according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by 11lein** [comment]
+1

**Comment by Drarok** [comment]
Looks like this was done https://www.npmjs.com/package/cordova-plugin-app-version
