### ISSUE TITLE
npmjs.com repository ?

### ISSUE THREAD

**Issue by devteamshippeo** [whiteoctober/cordova-plugin-app-version#60]
Hi,

In future, do you distribute your plugin with npmjs.com repository

I find this one in my first research https://www.npmjs.com/package/cordova-plugin-appversion but it's not you :-) 

Regards.

**Comment by Maistho** [comment]
Yeah, I set up a package at https://www.npmjs.com/package/cordova-plugin-app-version that should be fine to use.

**Comment by devteamshippeo** [comment]
Thanks !!!
