### ISSUE TITLE
$cordovaAppVersion.getAppVersion() doesn't exists in iOS

### ISSUE THREAD

**Issue by umarservishero** [whiteoctober/cordova-plugin-app-version#61]
``` javascript
    //show the App version
    if (ionic.Platform.isIOS() || ionic.Platform.isAndroid()) {
      $cordovaAppVersion.getAppVersion().then(function (version) {
        $scope.appVersion = version;
      });
    }
```

The above code works fine in android but somehow doesn't work in iOS

Saw the comment here http://forum.ionicframework.com/t/cordovaappversion-is-not-working/18695/4
but using $cordovaAppVersion.getVersionNumber() just simply doesn't work in both android and iOS

Thanks for helping me out here

**Comment by jason-engage** [comment]
@umarservishero hey did you get this to work, or this a real issue? Which version of iOS is it malfunctioning on?

**Comment by robksawyer** [comment]
Not working for me either. Anyone have any luck? 

Some of the code that I'm using:

```
angular.module('myproject.controllers', [
 'ngCordova'
])
```

```
.controller('MyController', function($rootScope, $scope, $cordovaAppVersion){

  //Get the application version and build number
  ionic.Platform.ready(function(){
    // will execute when device is ready, or immediately if the device is already ready.
    $cordovaAppVersion.getVersionNumber().then(
      function (version) {
        alert(version);
        $scope.appVersion = version;
      }
    );
	});
	
});
```

**Comment by robksawyer** [comment]
Spoke too soon. Fixed the issue by moving the code out of the controller into the `app.js` file. 
Here's a snippet:
```
.run(function($rootScope, $injector, $ionicPlatform, $cordovaAppVersion, $ionicPopup, SessionService) {

  $ionicPlatform.ready(function() {

    // will execute when device is ready, or immediately if the device is already ready.
    if(window.cordova){
      cordova.getAppVersion.getVersionNumber().then(
        function (version) {
          SessionService.persist('appVersion', version);
        }
      );
      cordova.getAppVersion.getVersionCode().then(
        function (code) {
          SessionService.persist('appVersionCode', code);
        }
      );
    }
  });
})
```

**Comment by jorgen-k** [comment]
robksawyers workaround do not work for me on IOS 8.

**Comment by christianjunk** [comment]
Hi!

I am using the following code inside a controller:

```javascript
$ionicPlatform.ready(function() {
      $cordovaAppVersion.getVersionNumber().then(function (version) {
        vm.version = version;
      });
      }, false);
```

When building the app using ``ionic prepare ios && ionic build ios`` and then deploy via Xcode  everything is working as expected.

Using the same code and building via PhoneGap Build will produce the error mentioned above:

```
Error: cordova.getAppVersion.getVersionNumber is not a function. (In 'cordova.getAppVersion.getVersionNumber(function(e){n.resolve(e)})', 'cordova.getAppVersion.getVersionNumber' is undefined)
getVersionNumber@file:///var/mobile/Containers/Bundle/Application/82BD08B2-62A1-4B29-AFC5-610E9A372C6C/API510Inspection.app/www/lib/ngCordova/dist/ng-cordova.min.js:7:3083
```

Perhaps there is a bug inside the plugin or ngCordova?

Kind regards,

Christian

My dev environment:

* Cordova 5.3.3
* Xcode 7.1
* Ionic CLI 1.7.8
* iOS 9.1 (iPhone 6)

**Comment by christianjunk** [comment]
I think I found a solution for my problem! I used an outdated version of the plugin in my `config.xml`:

```xml
<gap:plugin name="uk.co.whiteoctober.cordova.appversion"/>
```
Now I am using

```xml
<gap:plugin name="cordova-plugin-app-version" version="0.1.7" source="npm"/>
```

and everything is working.

**Comment by torstenfeld** [comment]
I do not get the plugin to work on iOS as well. 
My code in the app.js:
```
$ionicPlatform.ready(function() {
      if(window.cordova) {
        //$cordovaAppVersion.getVersionNumber().then(function (version) {
        cordova.getAppVersion.getVersionNumber().then(function (version) {
          appVersion = version;
          alert('appVersion: ' + appVersion);
        });
      }
    });
```

and plugin in config.xml:
```
<plugin name="cordova-plugin-app-version" spec="0.1.8" source="npm" />
```

I'm building the app with phonegap build and receive the error on starting the app on iOS:
```
'undefined' is not an object (evaluating 'cordova.getAppVersion.getVersionNumber')

Stacktrace (aktuellster Aufruf als erstes):

  at onPlatformReady (/var/mobile/Applications/FFD2B003-D95F-4B19-A56E-1830EC3ADEE9/Library/AppLoaderApps/1C4A307F-C4F6-4F03-8478-4AFD1F34722A/lib/ionic/js/ionic.bundle.js:2452:24)
  at fire (/var/mobile/Applications/FFD2B003-D95F-4B19-A56E-1830EC3ADEE9/Library/AppLoaderApps/1C4A307F-C4F6-4F03-8478-4AFD1F34722A/cordova.js:775:28)
  at d (/var/mobile/Applications/FFD2B003-D95F-4B19-A56E-1830EC3ADEE9/Library/AppLoaderApps/1C4A307F-C4F6-4F03-8478-4AFD1F34722A/lib/raven/raven.min.js:2:14031)
```

**Comment by physox** [comment]
I have the problem on iOS 9.2

$ionicPlatform.ready(function() {
      if(window.cordova) {
        //$cordovaAppVersion.getVersionNumber().then(function (version) {
        cordova.getAppVersion.getVersionNumber().then(function (version) {
          appVersion = version;
          alert('appVersion: ' + appVersion);
        });
      }
    });

getAppVersion is undefined

**Comment by sergiojup** [comment]
Hello,

I had the same issue and I solved it removing the plugin and later install by the command: 
"cordova plugin add https://github.com/whiteoctober/cordova-plugin-app-version" instead of "cordova plugin add cordova-plugin-app-version".

This is caused because the plugin was released to the version 0.18 and later was committed with version changes. When you install using the url you install the last commit version, and when you install by the name you install the last release done.

Best regards

**Comment by sergiojup** [comment]
I had the same issue in Android and I solved it removing the plugin and later installing it by the command "cordova plugin add https://github.com/whiteoctober/cordova-plugin-app-version" instead of "cordova plugin add cordova-plugin-app-version". 

In iOS I keep having problems, so this solution doesn't fix this problem in iOS .

I didn't try it, but maybe installing the release 0.1.7 by the command "cordova plugin add cordova-plugin-app-version@0.1.7" works.

**Comment by physox** [comment]
Ok, now i solved it for me. 
I am using Ionic 1.2.1 and Cordova 5.3.3 on an iPhone 4s with iOS 9.2.

I used the plugin version 0.1.7 and called 
    cordova.getAppVersion.getVersionNumber().then(function (version) { ... });
inside the function
    $ionicPlatform.ready(function() { ... });

**Comment by TomDoesRUG** [comment]
Same issue, downgrading to 0.1.7 worked

**Comment by h4nN** [comment]
Any NodeJS package tested and working?, it's  incredible... npm has a lot of packages not working; without tests, without good practices. Incredible! We need change it.

**Comment by ilyavinogradov** [comment]
I believe all you needed to do is `ionic state reset` to get the plugin downloaded and linked with your project (provided that you have ```"cordovaPlugins": [
<...>
    "cordova-plugin-app-version",
<...>
  ],```
in your `package.json`.)

Down grading to 0.1.7 worked for me, and updated the `/plugins` folder, then I upgraded to 0.1.8 - still works. Then to the latest (0.1.9) - still works! Before doing that - the plugin was in the global `.cordova` folder and was not packaged into the project, that's why it wasn't found.

**Comment by Drarok** [comment]
I can't speak for Ionic, but the current plugin definitely works using "plain" JavaScript:
```js
        cordova.getAppVersion().then(function (version) {
            console.log('Version is ' + JSON.stringify(version));
        });
```

**Comment by awaism551** [comment]
I had the same problem and using it in `$timout` AngularJS service did the trick for me 
`$timeout(function () {
            $scope.versionNumber = '';
            window.cordova.getAppVersion.getVersionNumber().then(function (version) {
                $scope.versionNumber = version;
            });
        });`
