### ISSUE TITLE
getAppName() & getPackageName() & getVersionCode() returns Version Number

### ISSUE THREAD

**Issue by web-slinger** [whiteoctober/cordova-plugin-app-version#64]
```
cordova.getAppVersion.getAppName().then(function (app_name) {
    $log.debug(app_name)
});
cordova.getAppVersion.getPackageName().then(function (package_name) {
    $log.debug(package_name)
});
cordova.getAppVersion.getVersionCode().then(function (version_code) {
    $log.debug(version_code)
});
cordova.getAppVersion.getVersionNumber().then(function (version) {
    $log.debug(version)
});
```

The above returns '2.0' for each iteration

I've just removed the plugin and added via git clone, I'm using this in angular

**Comment by Alex--Jin** [comment]
Same problem is here.

**Comment by web-slinger** [comment]
My problem was solved when i removed another app version plugin (https://github.com/bgta/net.bgta.phonegap.appversion) they share the same methods thus returning the version code for each.

**Comment by alidavid0418** [comment]
`getVersionCode()` is not working for me at the moment.
Is anyone helping me out? Thanks in advance.
