### ISSUE TITLE
Why is it async?

### ISSUE THREAD

**Issue by pke** [whiteoctober/cordova-plugin-app-version#65]
As far as I can see all the calls to actually get the version from the OS/Package are sync anyways. Why is this plugin then exposing an async calling pattern?

Wouldn't `cordova.appversion.xxx` be easier to call?

**Comment by Drarok** [comment]
I can't answer with authority since I wasn't around at the start of the project, but I believe it's standard Cordova plugin behaviour to use callbacks, [as documented here](https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html#the-javascript-interface).
