### ISSUE TITLE
Propose as an official apache plugin

### ISSUE THREAD

**Issue by jacargentina** [whiteoctober/cordova-plugin-app-version#7]
I think this should be "standard" for any apache cordova app.

Maybe u can "donate" the code to apache cordova folks to be renamed as official apache.cordova.appversion or something?

**Comment by Drarok** [comment]
It seems that it's on the Cordova Registry, which I feel is enough for now. 
![screen shot 2018-01-16 at 17 03 36](https://user-images.githubusercontent.com/55830/35001697-38b8aed8-fadf-11e7-8782-0d8db3e06bb8.png)
