### ISSUE TITLE
v0.1.8 kills iOS, v0.1.7 works. gap://ready iframe added

### ISSUE THREAD

**Issue by samkelleher** [whiteoctober/cordova-plugin-app-version#74]
Literally keeping the codebase the same apart from the two versions between `0.1.8` and `0.1.7`. iOS 4.0.1 on Cordova 6.0.0.

I get no errors, but for some reason, the body tag is replaced with the `gap://ready` iframe.

I wonder if there is a script error or something in the plugin causing `cordova.js` to fallback to rendering the iframe.

**Comment by Drarok** [comment]
I've tested `v0.1.9` and it works on iOS.
