### ISSUE TITLE
Feature Request - Build ID

### ISSUE THREAD

**Issue by 1marty4sale** [whiteoctober/cordova-plugin-app-version#77]
Not sure if this is even possible using cordova, but it being able to get the build ID would mean things can be done when app is first launched after install.  Could just check the build ID with the device's last recorded build ID to see if matches.

**Comment by Drarok** [comment]
Does `getVersionCode` address this need?

**Comment by DennisSmolek** [comment]
@1marty4sale Which BuildId property are you referring to specifically? The build of the OS or the version number/code of the app?

**Comment by 1marty4sale** [comment]
To be honest, I am struggling to remember, I wrote this a while ago.  I would assume the version number only changes when you change it yourself, so I wouldn't have been asking for that.  If there was a unique number generated every time the app is built, I would have meant that.  Although I'm sure most people are more diligent at changing the app version than I am so that would be sufficient for most people.
