### ISSUE TITLE
Error in WP8.1 using PhoneGap Build

### ISSUE THREAD

**Issue by Firzenizer** [whiteoctober/cordova-plugin-app-version#87]
There is some issue building for WP8.1+ in PGB. I get no errors and PGP says the plugin is correctly installed. Yet cordova.getAppVersion is undefined when trying to check version. I tried running my project using Visual Studio 2015 and everything worked just fine. Tested using WP10 device.

Any idea what is wrong?

**Comment by manoj529** [comment]
@Firzenizer  I tested it in windows phone10 and i received the same response i'e 1.0.0  even if i change version and create a new build, can you recheck and confirm is that working in windows phone 10.

**Comment by cadesalaberry** [comment]
I am having no issue using this plugin, can you try to explain your problem in greater details ?

**Comment by manoj529** [comment]
@cadesalaberry it's working fine. I had to make changes I config.xml and the delete the platform and then build it again.

**Comment by Drarok** [comment]
I have no way to test Windows platforms currently – is this issue resolved? If not, please re-open it.
