### ISSUE TITLE
Please provide a way to install this plugin with phonegap project

### ISSUE THREAD

**Issue by Toomavic** [whiteoctober/cordova-plugin-app-version#93]

**Comment by nikmartin** [comment]
Have you tried? http://docs.phonegap.com/phonegap-build/configuring/plugins/#importing-config You can install any cordova plugin in phonegap from npm

**Comment by Drarok** [comment]
Thanks @nikmartin. Given this plugin is specifically a _Cordova_ plugin, I'll close this issue.
