### ISSUE TITLE
Install problem -- how to set up.

### ISSUE THREAD

**Issue by newuser44** [whiteoctober/cordova-plugin-app-version#95]
I'm confused on what is needed to get this to work.

I have ngCordova installed.

I have a link to the js file in my html.
I have the ngCordova services added.

angular.module('myApp', ['ngCordova'])

Now I install this plug in.

To use this plugin do I need the ngCordova AND $cordovaAppVersion ???

Do I need to add any JS anywhere?

I know there is something I'm missing but not sure where I'm off.

Update. I added in the JS.
Looks like its finding it, but then I get an error

AppVersionPlugin.js:65 Uncaught ReferenceError: module is not defined
at AppVersionPlugin.js:65

The line it has a problem with is
module.exports = getAppVersion;

**Comment by Drarok** [comment]
Sorry, I've not used `ngCordova`, but given they appear to have [their own plugins ecosystem](http://ngcordova.com/docs/plugins/), it might be that it's not compatible with plain Cordova ones?
