### ISSUE TITLE
What data is this suppose to be getting?

### ISSUE THREAD

**Issue by newuser44** [whiteoctober/cordova-plugin-app-version#96]
I finally got this installed.  (I think)
Build an android apk. 
All the values are empty (version, build, name, package). 

I need to check the source... is this pulling the data from the config name, version  or from some android name?

**Comment by t2wu** [comment]
It's pulling version from config.xml.

**Comment by Drarok** [comment]
By default (when creating a new Cordova project), the version is `1.0.0`, so you should at least be able to see that in the callback?
