### ISSUE TITLE
Typeerror: cordova.getAppVersion is not function

### ISSUE THREAD

**Issue by dsemerida** [whiteoctober/cordova-plugin-app-version#97]
im trying to use this pluggin but i get this error  Typeerror: cordova.getAppVersion is not function , can you help me?

**Comment by Dev205** [comment]
When I was  using it with ionic my import was:

```
import {AppVersion} from "ionic-native";
```
I was getting the above error because it should've been getting the typings from @ionic-native/app-version, so i changed my import to:

```
import {AppVersion} from "@ionic-native/app-version";
```

**Comment by Drarok** [comment]
I'm afraid there's simply not enough information here for me to help, sorry.

* How did you install the plugin?
* What code are you running?
* When is your code running?

Using a fresh Cordova project, I've confirmed the following code works as expected:
```js
cordova.getAppVersion()
  .then(function (version) {
    console.log('version', version);
  });
```

**Comment by thamizhselvan93** [comment]
Please reopen the issue, the solution is not given yet

**Comment by Drarok** [comment]
@thamizhselvan93 there's no solution because there's no _problem_ as far as I can determine.

**Comment by jebbdomingo** [comment]
@Drarok the following doesn't work
>cordova.getAppVersion()
  .then(function (version) {
    console.log('version', version);
  });

tried executing it on `deviceready` event
