### ISSUE TITLE
the app version code encoding rules?

### ISSUE THREAD

**Issue by SaberDevel** [whiteoctober/cordova-plugin-app-version#98]
In ionic, I set config.xml: `version="0.1.5"`
```
appVersion.getVersionCode().then(function (versionCode) {
    console.log(versionCode);
});
```
console output:`105`

`version="0.1.15"`

console output:`115`

there are some phones that output:`1152`

i intend to set up a set of check and update mechanism based on app version code. how should I set up the remote version number according to the version of ionic?

run the app，from console output  the version code?

**Comment by Drarok** [comment]
I can't confirm this. If I set `version="0.1.5"` in `config.xml`, then `getVersionCode()` resolves to `"0.1.5"`.
